version: '3.3'
services:
  webserver:
    build:
      context: ./.docker/nginx-php
      dockerfile: Dockerfilelatest
    container_name: webserver 
    ports:
      - "8072:80"
    volumes:
      - ./storage/logs/nginx/:/var/log/nginx
      - ./config/sites/:/etc/nginx/sites-enabled/
      - $PROJECT_ROOT:/var/www

  webserver71:
    build:
      context: ./.docker/nginx-php
      dockerfile: Dockerfile71xdebug
    container_name: webserver71  
    ports:
      - "8071:80"
    volumes:
      - ./storage/logs/nginx/:/var/log/nginx
      - ./config/sites/:/etc/nginx/sites-enabled/
      - $PROJECT_ROOT:/var/www

  mysql:
    image: mysql:$MYSQL_VERSION
    container_name: mysql    
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./storage/data/mysql:/var/lib/mysql

  redis:
    image: redis:3.0
    container_name: redis
    ports:
        - "6379:6379"
    volumes:
      - ./storage/data/redis:/data

  workspace:
    build:
      context: ./.docker/workspace
    container_name: workspace
    ports:
      - "80:80"
    volumes:
      - $PROJECT_ROOT:/var/www/invoiceplane
      - ./storage/composer:/home/homestead/.composer/cache
    tty: true
